name: 'Sparrow Bot'
description: 'GitHub bot for automating repository maintenance tasks'
author: 'Sparrow'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  command:
    description: 'Command to run (stale, pr-title, auto-label, sync-labels, code-review)'
    required: true
  pr-title:
    description: 'PR title to validate (for pr-title command)'
    required: false
  pr-number:
    description: 'PR number (for pr-title command)'
    required: false
  commit-sha:
    description: 'Commit SHA (for pr-title command)'
    required: false
  issue-number:
    description: 'Issue number (for auto-label command)'
    required: false
  content:
    description: 'Content to analyze (for auto-label command)'
    required: false
  title:
    description: 'Title to analyze (for auto-label command)'
    required: false
  is-pr:
    description: 'Whether the item is a PR (for auto-label command)'
    required: false
    default: 'false'
  config-path:
    description: 'Path to config file'
    required: false
    default: '.github/sparrow-bot.json'
  use-azure:
    description: 'Whether to use Azure OpenAI instead of OpenAI (for code-review command)'
    required: false
    default: 'false'
  openai-api-key:
    description: 'OpenAI API key (for code-review command)'
    required: false
  azure-openai-api-key:
    description: 'Azure OpenAI API key (for code-review command with use-azure=true)'
    required: false
  azure-openai-endpoint:
    description: 'Azure OpenAI endpoint URL (for code-review command with use-azure=true)'
    required: false
  azure-openai-deployment:
    description: 'Azure OpenAI deployment name (for code-review command with use-azure=true)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd ${{ github.action_path }}
        npm ci
      shell: bash

    - name: Run command
      run: |
        cd ${{ github.action_path }}
        npm run cli ${{ inputs.command }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_TITLE: ${{ inputs.pr-title }}
        PR_NUMBER: ${{ inputs.pr-number }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        CONTENT: ${{ inputs.content }}
        TITLE: ${{ inputs.title }}
        IS_PR: ${{ inputs.is-pr }}
        CONFIG_PATH: ${{ inputs.config-path }}
        # OpenAI and Azure OpenAI settings
        SPARROW_USE_AZURE: ${{ inputs.use-azure }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        AZURE_OPENAI_API_KEY: ${{ inputs.azure-openai-api-key }}
        AZURE_OPENAI_ENDPOINT: ${{ inputs.azure-openai-endpoint }}
        AZURE_OPENAI_DEPLOYMENT: ${{ inputs.azure-openai-deployment }}

branding:
  icon: 'check-circle'
  color: 'blue'