name: Sparrow Bot with Azure OpenAI

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:     # Allow manual triggering
  pull_request:
    types: [opened, edited, synchronize, reopened]
  issues:
    types: [opened, edited]

jobs:
  stale:
    name: Process Stale Items
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Process stale items
        run: npx sparrow-bot stale
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate PR title
        run: npx sparrow-bot pr-title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Auto label
        run: npx sparrow-bot auto-label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          CONTENT: ${{ github.event.issue.body || github.event.pull_request.body }}
          TITLE: ${{ github.event.issue.title || github.event.pull_request.title }}
          IS_PR: ${{ github.event_name == 'pull_request' }}
  
  code-review:
    name: AI Code Review with Azure OpenAI
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create config file
        run: |
          mkdir -p .github
          cat > .github/sparrow-bot.json << EOF
          {
            "codeReview": {
              "skipReviewLabel": "skip-ai-review",
              "excludePatterns": [
                "\\.md$",
                "\\.json$",
                "\\.lock$"
              ],
              "maxComments": 10,
              "maxTokens": 2000,
              "createReview": true,
              "showConfidence": true,
              "addDisclaimer": true,
              "useAzure": true
            }
          }
          EOF
      
      - name: Run AI Code Review
        run: npx sparrow-bot code-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          # Azure OpenAI API credentials
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
